sudo: required
language: generic
services:
  - docker
env:
  matrix:
  - HHVM_VERSION=4.8.0
  - HHVM_VERSION=4.9.0
  - HHVM_VERSION=4.10.0
  - HHVM_VERSION=4.11.0
  - HHVM_VERSION=latest
install:
  - docker pull hhvm/hhvm:$HHVM_VERSION
script:
  - docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
